# -*- coding: utf-8 -*-
"""Day1_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h8AFk776A2MxReUK8l630p6rBToAOopN
"""

k=[int(i) for i in input("enter the list of values:").split()]
k.sort()
k.reverse()
print(k)